export enum SnapshotStatus {
  RECEIVED = 'RECEIVED',
  VALIDATED = 'VALIDATED',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  RETIRED = 'RETIRED',
}

export enum ImportRunStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
}

export enum ResourceType {
  CATALOG_METADATA = 'CATALOG_METADATA',
  REPOSITORY = 'REPOSITORY',
  REPOSITORY_SESSION = 'REPOSITORY_SESSION',
  SLIDES = 'SLIDES',
  TRANSCRIPT = 'TRANSCRIPT',
  VIDEO = 'VIDEO',
  WEBPAGE = 'WEBPAGE',
}

export enum ChunkSourceKind {
  TRANSCRIPT = 'TRANSCRIPT',
  CATALOG_METADATA = 'CATALOG_METADATA',
  REPOSITORY_SESSION = 'REPOSITORY_SESSION',
  SLIDES = 'SLIDES',
}
